[site]
title = "Yunfei Jia"
description = "Personal academic homepage of Yunfei Jia, PhD student at Washington University."
favicon = "/YJ.png"
last_updated = "September 24, 2026"

[author]
name = "Yunfei Jia"
title = "Ph.D. student"
institution = "Washington University in St. Louis"
avatar = "/YJ_profile.png"

[social]
email = "j.yunfei@wustl.edu"
location_url = "https://www.google.com/maps/place/Stephen+F.+and+Camilla+T.+Brauer+Hall/@38.6484222,-90.3027024,19z/data=!4m6!3m5!1s0x87d8caabb6a7a169:0xb12fbed88b02321c!8m2!3d38.6489089!4d-90.3021483!16s%2Fg%2F124sz676b?entry=ttu&g_ep=EgoyMDI2MDcyOC4wIKXMDSoASAFQAw%3D%3D"
location_details = [
  "Room 3011, Brauer Hall",
  "1 Brookings Drive,",
  "St. Louis, MO 63130, United States"
]
google_scholar = "https://scholar.google.com/citations?user=4J-02cIAAAAJ&hl=en"
orcid = "https://orcid.org/0000-0001-7236-1217"
linkedin = "https://www.linkedin.com/in/yunfei-jia-265543329/"

[features]
enable_likes = false
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["en", "zh"]
default_locale = "en"
mode = "auto"
fixed_locale = "en"
persist = true
switcher = true

[i18n.labels]
en = "English"
zh = "中文"

[[navigation]]
title = "Home"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

#[[navigation]]
#title = "Awards"
#type = "page"
#target = "awards"
#href = "/awards"

[[navigation]]
title = "Service"
type = "page"
target = "services"
href = "/services"

#[[navigation]]
#title = "CV"
#type = "page"
#target = "cv"
#href = "/cv"
