[[news]]
date = "2026-09"
tag = "论文"
content = "关于室内三手烟的综述论文发表于美国化学学会期刊 [*ES&T Air*](https://doi.org/10.1021/acsestair.5c00143) 。"

[[news]]
date = "2026-07"
tag = "历程"
content = "加入由工程学院 [Jenna Ditto 教授](https://engineering.washu.edu/faculty/Jenna-Ditto.html) 与医学院及附属Barnes-Jewish医院 [Andrew Kau 教授](https://physicians.wustl.edu/people/andrew-l-kau-md/) 共同领导，由美国国家卫生研究院(NIH)资助的项目*室内致敏原的演变* (项目基金 $427,600)。"

[[news]]
date = "2026-07"
tag = "奖项"
content = "获得 [*美国气溶胶学会 (AAAR)*](https://www.aaar.org/) 第44届年度会议参会资助 (资助金额 $600)。"

[[news]]
date = "2025-12"
tag = "历程"
content = "以全A/A+成绩修完博士项目全部课程。"

[[news]]
date = "2025-08"
tag = "服务"
content = "担任 [*气溶胶科学与工程中心 (CASE)*](https://aerosols.washu.edu/) 青年委员。"

[[news]]
date = "2025-05"
tag = "历程"
content = "顺利通过博士资格考试。🎉"

[[news]]
date = "2024-08"
tag = "奖项"
content = "获评*环境与化学系优秀学者* (奖金 $5,000)。"

[[news]]
date = "2024-08"
tag = "历程"
content = "入读圣路易斯华盛顿大学全额奖学金博士研究生！🎉"
